services:
  flask-app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - mysql-central
      - mysql-node2
      - mysql-node3
    networks:
      - steam-network

  mysql-central:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: steam_games_data_warehouse
    ports:
      - "3306:3306"
    volumes:
      - mysql-central-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - steam-network

  mysql-node2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: steam_games_data_warehouse
    ports:
      - "3307:3306"
    volumes:
      - mysql-node2-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - steam-network

  mysql-node3:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: steam_games_data_warehouse
    ports:
      - "3308:3306"
    volumes:
      - mysql-node3-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - steam-network

networks:
  steam-network:
    driver: bridge

volumes:
  mysql-central-data:
  mysql-node2-data:
  mysql-node3-data:
